### ISSUE TITLE
please update “How to cite”...

### ISSUE THREAD

**Issue by Pzoom522** [hugomailhot/morpholex-fr#1]
... so I can cite your work. Thanks!

**Comment by hugomailhot** [comment]
The paper is still in press, so for the moment you can use this :)

>Mailhot, H., Wilson, M. A., Macoir, J., Deacon, S. H., Sánchez-Gutiérrez, C. (in press). MorphoLex-FR: A derivational morphological database for 38,840 French words. Behavior Research Methods.

**Comment by Pzoom522** [comment]
Thanks!

**Comment by Pzoom522** [comment]
Also, do you have POS information for this French database?

**Comment by Pzoom522** [comment]
> Also, do you have POS information for this French database?

Sorry, my point is that **POS** information appears in [MorphoLex-en](https://github.com/hugomailhot/MorphoLex-en), but not in current version of Morpholex-fr. Would you please possibly add this field? Or could you just advice some French POS tools so that I can get words' POS by myself? Thanks in advance!

**Comment by hugomailhot** [comment]
Adding this would be a good idea. However it won't happen soon, as I'm taken by other projects at the moment.

How familiar are you with programming? There are a few Python libraries out there that can determine what parts-of-speech a word can belong to, and that support doing so in French.

Here is an example from the [Polyglot](https://polyglot.readthedocs.io/en/latest/POS.html) Python package.

**Comment by Pzoom522** [comment]
I love writing Python, but I'm not familiar with French... So I will start with Polyglot. Much thanks~
